---
title: "Análisis Estadístico Descriptivo: Fumadores, Correlación Entre Edad y Cigarros Fumados al Día, Diferencias de Consumo Entre Hombres y Mujeres"
shorttitle: "Análisis Estadístico Descriptivo de 1932 Fumadores"
course: Computación I
professor: Jesús Ochoa
duedate: 12/7/2024
author:
  - name: Armando Delfín
    corresponding: true
    affiliations:
      - ref: UCV
      - ref: DSP
  - name: Eduardo Longaart
    affiliations:
      - ref: UCV
      - ref: DSP
  - name: Sonia Eveligret
    affiliations: 
      - ref: UCV
      - ref: DSP
affiliations:
  - id: UCV
    name: Universidad Central De Venezuela
  - id: DSP
    name: Departamento de Estadística y Probabilidad
abstract: "En este trabajo de investigacion se realiza un análisis descriptivo sobre una base de datos que contiene un numero de observaciones plasmadas en un registro con 3900 hombres y mujeres que son fumadores, a traves del uso de graficos y de estadisticas descriptivas, para obtener informacion y posteriormente hacer un estudio que nos permita conocer si existe una relacion entre la edad de las personas, su sexo y el numero de cigarros que consumen por dia. Lo que sea desea tener como resultado de este trabajo de investigacion es una estimacion basica enfocada a todos lo registros que contienen informacion de las personas que son fumadoras regulares, y de forma practica a traves del uso de graficos explicar las caracteristicas que posee una persona fumadora acorde a su sexo, edad y la cantidad de cigarros que fumen por dia"

keywords: [keyword1, keyword2, keyword3]
bibliography: bibliography.bib
lang: es
format:
  apaquarto-pdf:
    documentmode: stu
    keep-tex: true
---

# Análisis Descriptivo

A continuacion, en las siguientes tablas se muestran estadísticas descriptivas para las variables en estudio, Toda la informacion respecto a los datos a manejar fue extraida de <https://www.kaggle.com/datasets/jacepranter/smoker-health-data,> de la cual se estudia solo a los 1932 fumadores activos de entre los 3900 registros que incluyen ex-fumadores.

-   En promedio, los fumadores consumen 18 cigarros diariamente, con una desviación estándar de 9 cigarros. Menos del 25% de ellos fuma más de 20 cigarros (un paquete) por día. La distribución es asimétrica positiva, y leptocúrtica.

-   En promedio, los fumadores tienen 48 años de edad, con una desviación estándar de 8 años. El 75% de ellos tiene 53 años o menos. La distribución es asimétrica positiva , y leptocúrtica.

-   De todas las personas en observación, 1105 son de sexo masculino, y 827 de sexo femenino. Representando el 57% y 43% respectivamente.

| Variable | Promedio | D. Estandar | Q1  | Q2  | Q3  | C.S  | Kurtosis |
|----------|----------|-------------|-----|-----|-----|------|----------|
| C.D      | 17.9     | 9.43        | 10  | 20  | 20  | 0.07 | 2.30     |
| EDAD     | 47.7     | 7.97        | 41  | 46  | 53  | 0.51 | 2.40     |

: Estadística Descriptiva Sobre las Variables Cuantitativas

| Sexo  | Frecuencia Absoluta | Frecuencia Relativa | Frecuencia Relativa Porcentual |
|---------------|----------------|----------------|-------------------------|
| M     | 1105                | 0.57                | 57%                            |
| F     | 827                 | 0.43                | 43%                            |
| TOTAL | 1932                | 1                   | 1                              |

: Frecuencias Relativas de los Fumadores Respecto a su Sexo

## Análisis Bivariante: ¿Existe relacion entre la edad de los fumadores y la cantidad de cigarros que consumen al día?

A traves del análisis descriptivo bivariante (coeficiente de correlacion de Pearson) y el uso de graficos se determino que existe correlacion inversa entre el número de cigarros que fuma una persona y su edad

| Covarianza | Índice de Correlación |
|:----------:|:---------------------:|
|   -5.30    |         -0.07         |

La covarianza entre las dos variables, edad, y cigarros consumidos al día, tienen un valor de covarianza negativo, lo que significa que tienen una relación negativa o inversa. A su vez, el índice de correlación, el cual nos indica la fuerza de la relación negativa antes descubierta es de -0.07. Teniendo en cuenta que una relación inversa puede llegar a un máximo de -1, ésta correlación parece ser muy tenue.

Para observar estas dos variables gráficamente, nos referimos a la siguiente figura

```{r}
#| echo: false

#Importación de la BBDD
pacman::p_load(tidyverse, pacman, DescTools, moments, forcats, readr)
setwd("C:/Users/arman/OneDrive/Escritorio/BBDD") 
Smoker_G7 <- read.csv("Smoker G7.csv")

#Limpieza de datos
DF1 <- na.omit(Smoker_G7) %>% 
  filter(current_smoker == "yes")
  DF1$sex <- factor(DF1$sex)
  DF1$current_smoker <- factor(DF1$current_smoker)

# Winsorize cigs_per_day

x <- DF1$cigs_per_day

cigs_cleaned <- Winsorize(x, minval = NULL, maxval = NULL,
                          probs = c(0,0.92), na.rm = TRUE, 
                          type = 1)

# Limpiar valores NA

Smoker_G7$cigs_per_day[is.na(Smoker_G7$cigs_per_day)] <- 18

DF1 <- Smoker_G7 %>%
  filter(current_smoker == "yes")

x <- DF1$cigs_per_day

cigs_cleaned <- Winsorize(x, minval = NULL, maxval = NULL,
                          probs = c(0,0.92), na.rm = TRUE, 
                          type = 1)
#Creación df_cleaned

df1_cleaned <- DF1 %>% 
  mutate(cigs_per_day = cigs_cleaned) %>% 
  separate_wider_delim(
    blood_pressure,
    delim = "/",
    names = c("systolic_pressure", "dystolic_pressure"))
  
df1_cleaned$systolic_pressure <- as.numeric(df1_cleaned$systolic_pressure)
df1_cleaned$dystolic_pressure <- as.numeric(df1_cleaned$dystolic_pressure)
#Gráficamos

 df3_bracket <- df1_cleaned %>%
      mutate(edades = cut(age, breaks = c(31, 33, 35, 37, 39, 41, 43, 45, 47 ,49,
                                          51,53,55,57,59,61,63,65,67,69)))
    
    df3_bracket %>%
      group_by(edades) %>%
      summarise(mean_cigs_per_day = mean(cigs_per_day)) %>%
      ggplot(aes(x = edades, y = mean_cigs_per_day)) +
      geom_point(size = 3,
                 colour = "turquoise") +
      geom_segment(aes(x = edades,
                       y = mean(df3_bracket$cigs_per_day),
                       xend = edades,
                       yend = mean_cigs_per_day),
                   colour = "orange") +
      geom_hline(yintercept = mean(df3_bracket$cigs_per_day),
                 colour = "gray", linewidth = 1) +
      theme(axis.text.x.bottom = element_text(angle = 20), text) +
      labs(title = 
             "Promedio de cigarrillos consumidos al día por rango de edades",
           x ="", y = "cigarrillos consumidos al día")
    
```

## Measures

## Procedure

# Results

# Discussion

## Limitations and Future Directions

## Conclusion

# References

<!-- References will auto-populate in the refs div below -->

::: {#refs}
:::

# Appendix

# Title for Appendix
